FROM python:3
USER root
WORKDIR /usr/src/app
ADD requirements_20200731.txt /usr/src/app
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install --no-install-recommends -y \
    curl \
    sudo \
    vim \
    git && \
    apt-get clean

RUN pip install -r requirements_20200731.txt

RUN jupyter serverextension enable --py jupyterlab
ENV DEBIAN_FRONTEND dialog